apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  {{- with .Values.ingressAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.kibana.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.kibana.serviceName }}
                port:
                  number: {{ .Values.kibana.servicePort }}
  {{- if .Values.tls }}
  tls:
    {{- toYaml .Values.tls | nindent 4 }}
  {{- end }}
