apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpd.fullname" . }}
  labels:
    {{- include "httpd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "httpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "httpd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FLUENTD_ADDRESS
              value: {{ .Values.logging.fluentdAddress | default (ternary (printf "%s-fluentd:24224" .Values.stackName) "fluentd:24224" (gt (len (toString .Values.stackName)) 0)) | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          {{- end }}
      restartPolicy: Always
